/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import ControllerImplementasi.ImplementasiPengembalian;
import ControllerInterface.PengembalianInterface;
import Model.ModelPengembalian;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class FormPengembalian extends javax.swing.JPanel {
 List <ModelPengembalian> record =new ArrayList<>();
    PengembalianInterface perpusservis;
    int row;
    /**
     * Creates new form FormPengembalian
     */
    public FormPengembalian() {
        initComponents();
        perpusservis=new ImplementasiPengembalian();
      this.refresdata();
        
    }
     void panggildata(){
        try {
            record = perpusservis.tampil();
        } catch (Exception e) {
        }
    
    }
     void isitabel(){
    Object data[][] = new Object[record.size()][6];
    int x = 0;
    for (ModelPengembalian ktm : record){
    data[x][0]=ktm.getNo_transaksi();
    data[x][1]=ktm.getNama();
    data[x][2]=ktm.getNpm();
    data[x][3]=ktm.getKode_buku();
    data[x][4]=ktm.getJudul_buku();
    data[x][5]=ktm.getTanggal();
    data[x][6]=ktm.getNama_pengarang();
    x++;
    }
    String judul[]={"No transksi","Nama","NPM","KODE BUKU","JUDUL BUKU","TGL","Pengarang"};
    jTable1.setModel(new DefaultTableModel(data,judul));
    }
    
     void refresdata(){
    isitabel();
    panggildata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Form Pengembalian");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("No. Transaksi : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nama :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("NPM :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 40, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Kode Buku : ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Judul Buku :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 70, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Pengarang Buku : ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 80, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 140, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 90, -1));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 140, -1));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 140, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 520, 140));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Cari : ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 280, -1));

        jButton1.setText("Cari");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        jButton2.setText("cari");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jButton3.setText("Pengembalian");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jButton4.setText("Batal");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel9.setText("Tanggal :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String no_trans=jTextField1.getText();
        String nama=jTextField2.getText();
        String npm=jTextField3.getText();
        String kode_buku=jTextField4.getText();
        String judul_buku=jTextField5.getText();
        String pengarang=jTextField6.getText();
        String tgl=jTextField8.getText();
        if(no_trans.trim().equals("") && nama.trim().equals("")&& npm.trim().equals("")&& kode_buku.trim().equals("")&& judul_buku.trim().equals("")&& pengarang.trim().equals("")&& tgl.trim().equals("")){
            JOptionPane.showMessageDialog(this,"Data Tidak Boleh Kosong");
        }else{
            try {
                ModelPengembalian perpus=new ModelPengembalian(null, null);
                perpus.setNo_transaksi(jTextField1.getText());
                perpus.setNama(jTextField2.getText());
                perpus.setNpm(jTextField3.getText());
                perpus.setKode_buku(jTextField4.getText());
                perpus.setJudul_buku(jTextField5.getText());
                perpus.setNama_pengarang(jTextField6.getText());
                perpus.setTanggal(jTextField8.getText());
                perpusservis.simpan(perpus);
                JOptionPane.showMessageDialog(this,"Data Telah Berhasil di Simpan");
                
            } catch (SQLException o) {
                System.out.println("gagal mengedit"+o);
                
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
